/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my_package;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author mniha
 */
public class FP3 extends  javax.swing.JFrame {

    /**
     * Creates new form FP3
     */
    
    public static String filename;
    double printans;
    VAF vaff=new VAF();
    Codesize cdsize=new Codesize();
    NewClick nclick=new NewClick();
    Validation vld=new Validation();
   
   
   
    
    public FP3() {
        initComponents();
        System.out.println("Init FP3");
    }
    public FP3(String msg,String lang) {
        initComponents();
        jTextField16.setText(msg);
        jTextField12.setText(lang);
        System.out.println("Cons2");
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jTextField16 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        jButton3.setText("jButton3");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CECS 543 Metrics Suite-"+NewClick.loc+"-"+FirstPage.fpname);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Weighting Factors");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Simple");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Average");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Complex");

        jLabel5.setText("External Inputs");

        jLabel6.setText("External Outputs");

        jLabel7.setText("External Inquiries");

        jLabel8.setText("Internal Logical Files");

        jLabel9.setText("External Interface Files");

        jLabel10.setText("Total Count");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jRadioButton1.setText("3");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setSelected(true);
        jRadioButton2.setText("4");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("6");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setText("4");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jRadioButton5.setSelected(true);
        jRadioButton5.setText("5");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        jRadioButton6.setText("7");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jRadioButton7.setText("3");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        jRadioButton8.setSelected(true);
        jRadioButton8.setText("4");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        jRadioButton9.setText("6");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });

        jRadioButton10.setText("7");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });

        jRadioButton12.setSelected(true);
        jRadioButton12.setText("10");
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });

        jRadioButton13.setText("15");
        jRadioButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton13ActionPerformed(evt);
            }
        });

        jRadioButton14.setText("5");
        jRadioButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton14ActionPerformed(evt);
            }
        });

        jRadioButton15.setSelected(true);
        jRadioButton15.setText("7");
        jRadioButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton15ActionPerformed(evt);
            }
        });

        jRadioButton16.setText("10");
        jRadioButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton16ActionPerformed(evt);
            }
        });

        jButton1.setText("Calculate Total Sum");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Value Adjustment Factors");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Compute FP with Code Size");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Change Language");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel11.setText("Language");

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });

        jButton6.setText("Compute FP with VAF");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });

        jLabel12.setText("VAF");

        jTabbedPane1.addTab("Function Points", jTabbedPane2);

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("New");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Open");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Save");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Close");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Preferences");

        jMenuItem7.setText("Languages");
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Metrics");

        jMenu7.setText("Function Points");

        jMenuItem9.setText("Enter FP Data");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem9);

        jMenuItem10.setText("Compute Code size");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem10);

        jMenu4.add(jMenu7);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Project Code");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Help");
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel7)))
                                                .addGap(39, 39, 39)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                                    .addComponent(jTextField5))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2)
                                                    .addComponent(jRadioButton1)
                                                    .addComponent(jRadioButton4)
                                                    .addComponent(jRadioButton7)
                                                    .addComponent(jRadioButton10)
                                                    .addComponent(jRadioButton14))
                                                .addGap(65, 65, 65)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jRadioButton5)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(jRadioButton12)
                                                                .addComponent(jRadioButton8, javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jRadioButton15, javax.swing.GroupLayout.Alignment.LEADING)))
                                                        .addGap(106, 106, 106)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jRadioButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jRadioButton6)
                                                            .addComponent(jRadioButton13)
                                                            .addComponent(jRadioButton16)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel3)
                                                        .addGap(85, 85, 85)
                                                        .addComponent(jLabel4))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jRadioButton2)
                                                        .addGap(112, 112, 112)
                                                        .addComponent(jRadioButton3))))
                                            .addComponent(jButton5))
                                        .addGap(156, 156, 156))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(320, 320, 320)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(187, 187, 187)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField13, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField15, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField10)
                                    .addComponent(jTextField9)
                                    .addComponent(jTextField8)
                                    .addComponent(jTextField7)
                                    .addComponent(jTextField6)))
                            .addComponent(jLabel10))
                        .addGap(383, 383, 383))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(467, 467, 467)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton3)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton5)
                            .addComponent(jRadioButton6)
                            .addComponent(jLabel6))))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton8)
                            .addComponent(jRadioButton7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton10)
                            .addComponent(jRadioButton12)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton13)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton14)
                    .addComponent(jRadioButton15)
                    .addComponent(jRadioButton16)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(11, 11, 11)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(7, 7, 7)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton9.isSelected()) 
    {
     jRadioButton7.setSelected(false);
     jRadioButton8.setSelected(false);
      
    }    
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String a1=jTextField1.getText();
        int    a2=Integer.parseInt(a1);
        int tot1=0;
        
          if(jRadioButton1.isSelected())
          {   
              String  r1=jRadioButton1.getText();
              int rad1=Integer.parseInt(r1);
               tot1=a2*rad1;
               String tot2=Integer.toString(tot1);
               jTextField6.setText(tot2);
             
              
     }
          else if(jRadioButton2.isSelected())
          {   
              String  r1=jRadioButton2.getText();
              int rad1=Integer.parseInt(r1);
               tot1=a2*rad1;
               String tot2=Integer.toString(tot1);
               jTextField6.setText(tot2);
             
              
     }
          else
          {
          if(jRadioButton3.isSelected())
          {   
              String  r1=jRadioButton3.getText();
              int rad1=Integer.parseInt(r1);
               tot1=a2*rad1;
               String tot2=Integer.toString(tot1);
               jTextField6.setText(tot2);
             
          }   
     }
         String b1=jTextField2.getText();
        int    b2=Integer.parseInt(b1);
        int tot3=0;
        
          if(jRadioButton4.isSelected())
          {   
              String  r1=jRadioButton4.getText();
              int rad1=Integer.parseInt(r1);
               tot3=b2*rad1;
               String tot4=Integer.toString(tot3);
               jTextField7.setText(tot4);
             
              
     }
          else if(jRadioButton5.isSelected())
          {   
              String  r1=jRadioButton5.getText();
              int rad1=Integer.parseInt(r1);
               tot3=b2*rad1;
               String tot4=Integer.toString(tot3);
               jTextField7.setText(tot4);
             
              
     }
          else
          {
          if(jRadioButton6.isSelected())
          {   
              String  r1=jRadioButton6.getText();
              int rad1=Integer.parseInt(r1);
               tot3=b2*rad1;
               String tot4=Integer.toString(tot3);
               jTextField7.setText(tot4);
             
          }   
          
     }
          String c1=jTextField3.getText();
        int    c2=Integer.parseInt(c1);
        int tot5=0;
        
          if(jRadioButton7.isSelected())
          {   
              String  r1=jRadioButton7.getText();
              int rad1=Integer.parseInt(r1);
               tot5=c2*rad1;
               String tot6=Integer.toString(tot5);
               jTextField8.setText(tot6);
             
              
     }
          else if(jRadioButton8.isSelected())
          {   
              String  r1=jRadioButton8.getText();
              int rad1=Integer.parseInt(r1);
               tot5=c2*rad1;
               String tot6=Integer.toString(tot5);
               jTextField8.setText(tot6);
             
              
     }
          else
          {
          if(jRadioButton9.isSelected())
          {   
              String  r1=jRadioButton9.getText();
              int rad1=Integer.parseInt(r1);
               tot5=c2*rad1;
               String tot6=Integer.toString(tot5);
               jTextField8.setText(tot6);
             
          }   
     }
          String d1=jTextField4.getText();
        int    d2=Integer.parseInt(d1);
        int tot7=0;
        
          if(jRadioButton10.isSelected())
          {   
              String  r1=jRadioButton10.getText();
              int rad1=Integer.parseInt(r1);
               tot7=d2*rad1;
               String tot8=Integer.toString(tot7);
               jTextField9.setText(tot8);
             
              
     }
          else if(jRadioButton12.isSelected())
          {   
              String  r1=jRadioButton12.getText();
              int rad1=Integer.parseInt(r1);
               tot7=d2*rad1;
               String tot8=Integer.toString(tot7);
               jTextField9.setText(tot8);
             
              
     }
          else
          {
          if(jRadioButton13.isSelected())
          {   
              String  r1=jRadioButton13.getText();
              int rad1=Integer.parseInt(r1);
               tot7=d2*rad1;
               String tot8=Integer.toString(tot7);
               jTextField9.setText(tot8);
             
          }   
     }
         String e1=jTextField5.getText();
        int    e2=Integer.parseInt(e1);
        int tot9=0;
        
          if(jRadioButton14.isSelected())
          {   
              String  r1=jRadioButton14.getText();
              int rad1=Integer.parseInt(r1);
               tot9=e2*rad1;
               String tot10=Integer.toString(tot9);
               jTextField10.setText(tot10);
             
              
     }
          else if(jRadioButton15.isSelected())
          {   
              String  r1=jRadioButton15.getText();
              int rad1=Integer.parseInt(r1);
               tot9 =e2*rad1;
               String tot10=Integer.toString(tot9);
               jTextField10.setText(tot10);
             
              
     }
          else
          {
          if(jRadioButton16.isSelected())
          {   
              String  r1=jRadioButton16.getText();
              int rad1=Integer.parseInt(r1);
               tot9=e2*rad1;
               String tot10=Integer.toString(tot9);
               jTextField10.setText(tot10);
             
          }   
          
     }
           if(Integer.parseInt(jTextField1.getText())<0 ||Integer.parseInt(jTextField2.getText())<0||Integer.parseInt(jTextField3.getText())<0||Integer.parseInt(jTextField4.getText())<0||Integer.parseInt(jTextField5.getText())<0)
           {
               vld.setVisible(true);
           }
          int sum=tot1+tot3+tot5+tot7+tot9;
          String fsum=Integer.toString(sum);
          //String vaf=jTextField16.getText().toString();
         // double vaff=Double.parseDouble(vaf);
          //double finalans= sum *(0.65+0.01*vaff);
         // String fnl=Double.toString(finalans);
          jTextField11.setText(fsum);
          
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
    if(jRadioButton1.isSelected()) 
    {
     jRadioButton2.setSelected(false);
     jRadioButton3.setSelected(false);
    }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
          if(jRadioButton2.isSelected()) 
    {
     jRadioButton1.setSelected(false);
     jRadioButton3.setSelected(false);
    }
       
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton3.isSelected()) 
    {
     jRadioButton1.setSelected(false);
     jRadioButton2.setSelected(false);
      
    }    
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
         if(jRadioButton4.isSelected()) 
    {
     jRadioButton5.setSelected(false);
     jRadioButton6.setSelected(false);
      
    }    
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
           // TODO add your handling code here:
           if(jRadioButton5.isSelected()) 
    {
     jRadioButton4.setSelected(false);
     jRadioButton6.setSelected(false);
      
    }    
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton6.isSelected()) 
    {
     jRadioButton4.setSelected(false);
     jRadioButton5.setSelected(false);
      
    }  
        
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton10.isSelected()) 
    {
     jRadioButton13.setSelected(false);
     jRadioButton12.setSelected(false);
      
    }    
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton7.isSelected()) 
    {
     jRadioButton8.setSelected(false);
     jRadioButton9.setSelected(false);
      
    }    
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
   if(jRadioButton8.isSelected()) 
    {
     jRadioButton7.setSelected(false);
     jRadioButton9.setSelected(false);
      
    }            // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton12.isSelected()) 
    {
     jRadioButton10.setSelected(false);
     jRadioButton13.setSelected(false);
      
    }    
    }//GEN-LAST:event_jRadioButton12ActionPerformed

    private void jRadioButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton13ActionPerformed
        // TODO add your handling code here:
            if(jRadioButton13.isSelected()) 
    {
     jRadioButton10.setSelected(false);
     jRadioButton12.setSelected(false);
    }
    }//GEN-LAST:event_jRadioButton13ActionPerformed

    private void jRadioButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton14ActionPerformed
        // TODO add your handling code here:
         if(jRadioButton14.isSelected()) 
    {
     jRadioButton15.setSelected(false);
     jRadioButton16.setSelected(false);
    }
    }//GEN-LAST:event_jRadioButton14ActionPerformed

    private void jRadioButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton15ActionPerformed
        // TODO add your handling code here:
            if(jRadioButton15.isSelected()) 
    {
     jRadioButton14.setSelected(false);
     jRadioButton16.setSelected(false);
    }
    }//GEN-LAST:event_jRadioButton15ActionPerformed

    private void jRadioButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton16ActionPerformed
        // TODO add your handling code here:
            if(jRadioButton16.isSelected()) 
    {
     jRadioButton14.setSelected(false);
     jRadioButton15.setSelected(false);
    } 
    }//GEN-LAST:event_jRadioButton16ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
       vaff.setVisible(true);

      //jTextField16.setText(vaff.jTextField1.getText());
     
      // vaff.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String a1=jTextField1.getText();
        int    a2=Integer.parseInt(a1);
        int tot1=0;
        
          if(jRadioButton1.isSelected())
          {   
              String  r1=jRadioButton1.getText();
              int rad1=Integer.parseInt(r1);
               tot1=a2*rad1;
               String tot2=Integer.toString(tot1);
               jTextField6.setText(tot2);
             
              
     }
          else if(jRadioButton2.isSelected())
          {   
              String  r1=jRadioButton2.getText();
              int rad1=Integer.parseInt(r1);
               tot1=a2*rad1;
               String tot2=Integer.toString(tot1);
               jTextField6.setText(tot2);
             
              
     }
          else
          {
          if(jRadioButton3.isSelected())
          {   
              String  r1=jRadioButton3.getText();
              int rad1=Integer.parseInt(r1);
               tot1=a2*rad1;
               String tot2=Integer.toString(tot1);
               jTextField6.setText(tot2);
             
          }   
     }
         String b1=jTextField2.getText();
        int    b2=Integer.parseInt(b1);
        int tot3=0;
        
          if(jRadioButton4.isSelected())
          {   
              String  r1=jRadioButton4.getText();
              int rad1=Integer.parseInt(r1);
               tot3=b2*rad1;
               String tot4=Integer.toString(tot3);
               jTextField7.setText(tot4);
             
              
     }
          else if(jRadioButton5.isSelected())
          {   
              String  r1=jRadioButton5.getText();
              int rad1=Integer.parseInt(r1);
               tot3=b2*rad1;
               String tot4=Integer.toString(tot3);
               jTextField7.setText(tot4);
             
              
     }
          else
          {
          if(jRadioButton6.isSelected())
          {   
              String  r1=jRadioButton6.getText();
              int rad1=Integer.parseInt(r1);
               tot3=b2*rad1;
               String tot4=Integer.toString(tot3);
               jTextField7.setText(tot4);
             
          }   
          
     }
          String c1=jTextField3.getText();
        int    c2=Integer.parseInt(c1);
        int tot5=0;
        
          if(jRadioButton7.isSelected())
          {   
              String  r1=jRadioButton7.getText();
              int rad1=Integer.parseInt(r1);
               tot5=c2*rad1;
               String tot6=Integer.toString(tot5);
               jTextField8.setText(tot6);
             
              
     }
          else if(jRadioButton8.isSelected())
          {   
              String  r1=jRadioButton8.getText();
              int rad1=Integer.parseInt(r1);
               tot5=c2*rad1;
               String tot6=Integer.toString(tot5);
               jTextField8.setText(tot6);
             
              
     }
          else
          {
          if(jRadioButton9.isSelected())
          {   
              String  r1=jRadioButton9.getText();
              int rad1=Integer.parseInt(r1);
               tot5=c2*rad1;
               String tot6=Integer.toString(tot5);
               jTextField8.setText(tot6);
             
          }   
     }
          String d1=jTextField4.getText();
        int    d2=Integer.parseInt(d1);
        int tot7=0;
        
          if(jRadioButton10.isSelected())
          {   
              String  r1=jRadioButton10.getText();
              int rad1=Integer.parseInt(r1);
               tot7=d2*rad1;
               String tot8=Integer.toString(tot7);
               jTextField9.setText(tot8);
             
              
     }
          else if(jRadioButton12.isSelected())
          {   
              String  r1=jRadioButton12.getText();
              int rad1=Integer.parseInt(r1);
               tot7=d2*rad1;
               String tot8=Integer.toString(tot7);
               jTextField9.setText(tot8);
             
              
     }
          else
          {
          if(jRadioButton13.isSelected())
          {   
              String  r1=jRadioButton13.getText();
              int rad1=Integer.parseInt(r1);
               tot7=d2*rad1;
               String tot8=Integer.toString(tot7);
               jTextField9.setText(tot8);
             
          }   
     }
         String e1=jTextField5.getText();
        int    e2=Integer.parseInt(e1);
        int tot9=0;
        
          if(jRadioButton14.isSelected())
          {   
              String  r1=jRadioButton14.getText();
              int rad1=Integer.parseInt(r1);
               tot9=e2*rad1;
               String tot10=Integer.toString(tot9);
               jTextField10.setText(tot10);
             
              
     }
          else if(jRadioButton15.isSelected())
          {   
              String  r1=jRadioButton15.getText();
              int rad1=Integer.parseInt(r1);
               tot9 =e2*rad1;
               String tot10=Integer.toString(tot9);
               jTextField10.setText(tot10);
             
              
     }
          else
          {
          if(jRadioButton16.isSelected())
          {   
              String  r1=jRadioButton16.getText();
              int rad1=Integer.parseInt(r1);
               tot9=e2*rad1;
               String tot10=Integer.toString(tot9);
               jTextField10.setText(tot10);
             
          }   
          
     }
          int sum=tot1+tot3+tot5+tot7+tot9;
          String fsum=Integer.toString(sum);
          //String vaf=jTextField16.getText().toString();
         // double vaff=Double.parseDouble(vaf);
          //double finalans= sum *(0.65+0.01*vaff);
         // String fnl=Double.toString(finalans);
          jTextField11.setText(fsum);
          
        
         jTextField16.setText(vaff.msg);
         int fp1=0,fp2=0;
       fp1=Integer.parseInt(jTextField11.getText().toString());
        
        fp2=Integer.parseInt(jTextField16.getText().toString());
        
        double vp1=(0.65+(0.01*fp2));
         printans=fp1*vp1;
        jTextField13.setText(Double.toString(printans));
       
         
       
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        cdsize.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTextField12.setText(cdsize.lang);
         jTextField12.setText(cdsize.lang);
         String anscd=jTextField12.getText();
         if(anscd.matches("Assembler"))
         {
            int ac1=(int)printans*337;
             jTextField15.setText(Integer.toString(ac1));
         }
         else if(anscd.matches("Ada 95"))
         {
             int ac1=(int)printans*154;
            jTextField15.setText(Integer.toString(ac1));
         }
        else if(anscd.matches("C"))
         {
             int ac1=(int)printans*148;
            jTextField15.setText(Integer.toString(ac1));
         }
        else if(anscd.matches("CPP"))
         {
             int ac1=(int)printans*59;
             jTextField15.setText(Integer.toString(ac1));
         }
        else if(anscd.matches("C#"))
         {
             int ac1=(int)printans*58;
              jTextField15.setText(Integer.toString(ac1));
           }
        else if(anscd.matches("COBOL"))
         {
             int ac1=(int)printans*80;
             jTextField15.setText(Integer.toString(ac1));
         }
         else if(anscd.matches("FORTRAN"))
         {
             int ac1=(int)printans*90;
             jTextField15.setText(Integer.toString(ac1));
         }
        else if(anscd.matches("HTML"))
         {
             int ac1=(int)printans*43;
             jTextField15.setText(Integer.toString(ac1));
         }
        else if(anscd.matches("Java"))
         {
             int ac1=(int)printans*55;
             jTextField15.setText(Integer.toString(ac1));
         }
        else if(anscd.matches("JavaScript"))
         {
             int ac1=(int)printans*54;
             jTextField15.setText(Integer.toString(ac1));
         }
        else if(anscd.matches("VBScript"))
         {
             int ac1=(int)printans*38;
             jTextField15.setText(Integer.toString(ac1));
         }
        else if(anscd.matches("VB"))
         {
             int ac1=(int)printans*50;
            jTextField15.setText(Integer.toString(ac1));
         }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        String i1=jTextField1.getText().toString();
        Boolean rad1=jRadioButton1.isSelected();
        Boolean rad2=jRadioButton2.isSelected();
        Boolean rad3=jRadioButton3.isSelected();
        String i6=jTextField6.getText().toString();
        String i2=jTextField2.getText().toString();
         Boolean rad4=jRadioButton4.isSelected();
        Boolean rad5=jRadioButton5.isSelected();
        Boolean rad6=jRadioButton6.isSelected();
        String i7=jTextField7.getText().toString();
         String i3=jTextField3.getText().toString();
        Boolean rad7=jRadioButton7.isSelected();
        Boolean rad8=jRadioButton8.isSelected();
        Boolean rad9=jRadioButton9.isSelected();
        String i8=jTextField8.getText().toString();
         String i4=jTextField4.getText().toString();
        Boolean rad10=jRadioButton10.isSelected();
        Boolean rad12=jRadioButton12.isSelected();
        Boolean rad13=jRadioButton13.isSelected();
        String i9=jTextField9.getText().toString();
         String i5=jTextField5.getText().toString();
        Boolean rad14=jRadioButton14.isSelected();
        Boolean rad15=jRadioButton15.isSelected();
        Boolean rad16=jRadioButton16.isSelected();
        String i10=jTextField10.getText().toString();
        String i11=jTextField11.getText().toString();
        String i16=jTextField16.getText().toString();
        String i13=jTextField13.getText().toString();
        String i12=jTextField12.getText().toString();
        String i15=jTextField15.getText().toString();
        

        
        //System.out.println(i1);
        //System.out.println(i2);
        String deli=";";
        String combine = i1.concat(deli).concat(rad1.toString()).concat(deli).concat(rad2.toString()).concat(deli).concat(rad3.toString()).concat(deli).concat(i6).concat(deli).concat(i2).concat(deli).concat(rad4.toString().concat(deli)).concat(rad5.toString()).concat(deli).concat(rad6.toString()).concat(deli).concat(i7).concat(deli).
               concat(i3).concat(deli).concat(rad7.toString()).concat(deli).concat(rad8.toString()).concat(deli).concat(rad9.toString()).concat(deli).concat(i8).concat(deli).concat(i4).concat(deli).concat(rad10.toString().concat(deli)).concat(rad12.toString()).concat(deli).concat(rad13.toString()).concat(deli).concat(i9).concat(deli)
                .concat(i5).concat(deli).concat(rad14.toString()).concat(deli).concat(rad15.toString()).concat(deli).concat(rad16.toString()).concat(deli).concat(i10).concat(deli).concat(i11).concat(deli).concat(i16).concat(deli).concat(i13).concat(deli).concat(i12).concat(deli).concat(i15);
        System.out.println(combine);
       // String pathii=nclick.loc+".ms";
    //NewClick(pathi);
     System.out.println("INside funciton");
       // nclick.loc=nclick.projname.getText().toString();
       
        
    System.out.println(nclick.projname.getText());
        //NewClick(pathi);
         String toString = new JFileChooser().getFileSystemView().getDefaultDirectory().toString();
    System.out.println(nclick.projname.getText().toString());
    File dir = new File(new JFileChooser().getFileSystemView().getDefaultDirectory().toString()
            +"\\CECS543");
dir.mkdirs();



String  tmp = dir + "\\"+ filename+FirstPage.fpname+".ms";
        
   // File dir = new File(new JFileChooser().getFileSystemView().getDefaultDirectory().toString() +"\\CECS543");
dir.mkdirs();
//File tmp = new File(dir+"\\"+ pathii);
        try{
              BufferedWriter writer = new BufferedWriter(new FileWriter(tmp));
                                                                        
    writer.write(combine);
    
    writer.close();}
        catch(Exception e)
        
        {
        e.printStackTrace();
        }  

        
        
        
        
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        //System.out.println("Durgesh here");
        JFileChooser fileChooser = new JFileChooser();
//fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));


System.out.println(new JFileChooser().getFileSystemView().getDefaultDirectory().toString() + "\\CECS543");
        fileChooser.setCurrentDirectory(new File(new JFileChooser().getFileSystemView().getDefaultDirectory().toString() + "\\CECS543"
        
        ));
int result = fileChooser.showOpenDialog(this);
if (result == JFileChooser.APPROVE_OPTION) {
    File selectedFile = fileChooser.getSelectedFile();
    System.out.println("Selected file: " + selectedFile.getAbsolutePath());
    dispose();
   setVisible(true);
   try 
{ 
	FileReader inputFile = new FileReader(selectedFile.getAbsolutePath());
      
    try 
    { 
    	Scanner parser = new Scanner(inputFile); 
        while (parser.hasNextLine()) 
        { 
		 String line = parser.nextLine(); 
	        String[] att = line.split(";"); 
		    jTextField1.setText(att[0]);
                    System.out.println(jTextField1.getText());
                    if(att[1].matches("true"))
                    {
                        jRadioButton1.setSelected(true);
                    }
                    if(att[2].matches("true"))
                    {
                        jRadioButton2.setSelected(true);
                    }
                    if(att[3].matches("true"))
                    {
                        jRadioButton3.setSelected(true);
                    }
                    jTextField6.setText(att[4]);
                    jTextField2.setText(att[5]); 
                    if(att[6].matches("true"))
                    {
                        jRadioButton4.setSelected(true);
                    }
                    if(att[7].matches("true"))
                    {
                        jRadioButton5.setSelected(true);
                    }
                    if(att[8].matches("true"))
                    {
                        jRadioButton6.setSelected(true);
                    }
                    jTextField7.setText(att[9]);
                    jTextField3.setText(att[10]); 
                    if(att[11].matches("true"))
                    {
                        jRadioButton7.setSelected(true);
                    }
                    if(att[12].matches("true"))
                    {
                        jRadioButton8.setSelected(true);
                    }
                    if(att[13].matches("true"))
                    {
                        jRadioButton9.setSelected(true);
                    }
                    jTextField8.setText(att[14]);
                    jTextField4.setText(att[15]); 
                    if(att[16].matches("true"))
                    {
                        jRadioButton10.setSelected(true);
                    }
                    if(att[17].matches("true"))
                    {
                        jRadioButton12.setSelected(true);
                    }
                    if(att[18].matches("true"))
                    {
                        jRadioButton13.setSelected(true);
                    }
                    jTextField9.setText(att[19]);
                    jTextField5.setText(att[20]); 
                    if(att[21].matches("true"))
                    {
                        jRadioButton14.setSelected(true);
                    }
                    if(att[22].matches("true"))
                    {
                        jRadioButton15.setSelected(true);
                    }
                    if(att[23].matches("true"))
                    {
                        jRadioButton16.setSelected(true);
                    }
                    jTextField10.setText(att[24]);
                    jTextField11.setText(att[25]);
                    jTextField16.setText(att[26]);
                    jTextField13.setText(att[27]);
                    jTextField12.setText(att[28]);
                    jTextField15.setText(att[29]);
                    
			 
		 
                  
        } 
                 
    } 
    finally 
    { 
    	inputFile.close(); 
    } 
} 
catch(FileNotFoundException exception) 
{ 
	System.out.println(selectedFile.getAbsolutePath() + " not found"); 
} 
catch(IOException exception) 
{ 
	System.out.println("Unexpected I/O error occured."); 
} 
   
    
}

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        nclick.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
       FirstPage.fpname= JOptionPane.showInputDialog( this,"Enter FP Name");      
        new FP3().setVisible(true);
        
        
        
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
         //new FP3().setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FP3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FP3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FP3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FP3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FP3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem9;
    public static javax.swing.JRadioButton jRadioButton1;
    public static javax.swing.JRadioButton jRadioButton10;
    public static javax.swing.JRadioButton jRadioButton12;
    public static javax.swing.JRadioButton jRadioButton13;
    public static javax.swing.JRadioButton jRadioButton14;
    public static javax.swing.JRadioButton jRadioButton15;
    public static javax.swing.JRadioButton jRadioButton16;
    public static javax.swing.JRadioButton jRadioButton2;
    public static javax.swing.JRadioButton jRadioButton3;
    public static javax.swing.JRadioButton jRadioButton4;
    public static javax.swing.JRadioButton jRadioButton5;
    public static javax.swing.JRadioButton jRadioButton6;
    public static javax.swing.JRadioButton jRadioButton7;
    public static javax.swing.JRadioButton jRadioButton8;
    public static javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    public static javax.swing.JTextField jTextField1;
    public static javax.swing.JTextField jTextField10;
    public static javax.swing.JTextField jTextField11;
    public static javax.swing.JTextField jTextField12;
    public static javax.swing.JTextField jTextField13;
    public static javax.swing.JTextField jTextField15;
    public static javax.swing.JTextField jTextField16;
    public javax.swing.JTextField jTextField2;
    public static javax.swing.JTextField jTextField3;
    public static javax.swing.JTextField jTextField4;
    public static javax.swing.JTextField jTextField5;
    public static javax.swing.JTextField jTextField6;
    public static javax.swing.JTextField jTextField7;
    public static javax.swing.JTextField jTextField8;
    public static javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    void SetVisible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
